# Generated by Django 5.0.7 on 2026-03-05 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support_chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='support_message',
            options={'ordering': ['created_at'], 'verbose_name': 'Саппорт_сообщение', 'verbose_name_plural': 'Саппорт_сообщения'},
        ),
        migrations.RenameField(
            model_name='support_message',
            old_name='receiver_id',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='support_message',
            old_name='sender_id',
            new_name='sender',
        ),
    ]
