# Generated by Django 5.0.7 on 2026-03-06 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_chat', '0002_alter_support_message_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='support_message',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='support_chat.support_message'),
        ),
    ]
