# Generated by Django 5.0.7 on 2026-02-28 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lifes',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 1, 7, 57, 48, 794559, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='phoneverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 28, 8, 7, 48, 794559, tzinfo=datetime.timezone.utc)),
        ),
    ]
