# Generated by Django 5.0.7 on 2026-02-01 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_emailverification_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='streak_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 2, 9, 28, 54, 84000, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='phoneverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 1, 9, 38, 54, 84000, tzinfo=datetime.timezone.utc)),
        ),
    ]
