# Generated by Django 5.0.7 on 2026-02-28 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_lifes_alter_emailverification_expires_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='lifes',
            new_name='lives',
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 1, 7, 59, 18, 278890, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='phoneverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 28, 8, 9, 18, 278890, tzinfo=datetime.timezone.utc)),
        ),
    ]
