# Generated by Django 5.0.7 on 2026-02-28 08:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_emailverification_expires_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='lives',
            new_name='lifes',
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 1, 8, 25, 50, 952851, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='phoneverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 28, 8, 35, 50, 953857, tzinfo=datetime.timezone.utc)),
        ),
    ]
