# Generated by Django 5.0.7 on 2026-02-01 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_emailverification_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_session_date',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 2, 11, 30, 55, 235183, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='phoneverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 1, 11, 40, 55, 235183, tzinfo=datetime.timezone.utc)),
        ),
    ]
