# Generated by Django 5.0.7 on 2026-03-05 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_emailverification_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 6, 14, 24, 53, 54495, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='phoneverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 5, 14, 34, 53, 54495, tzinfo=datetime.timezone.utc)),
        ),
    ]
