# Generated by Django 5.0.7 on 2026-03-06 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_emailverification_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 7, 11, 3, 44, 90355, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='phoneverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 6, 11, 13, 44, 90355, tzinfo=datetime.timezone.utc)),
        ),
    ]
