# Generated by Django 5.0.7 on 2026-02-12 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_nickname_user_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 13, 12, 33, 48, 844413, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='phoneverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 12, 12, 43, 48, 846418, tzinfo=datetime.timezone.utc)),
        ),
    ]
