# Generated by Django 5.0.7 on 2026-03-25 14:30

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_emailverification_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 26, 14, 30, 3, 467363, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='phoneverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 25, 14, 40, 3, 467363, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fcm_token', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
